class Solution:
    """
    @param s: a string
    @param t: a string
    @return: the minimum substring of S
    """
    def min_window(self, s, t):
        # Write your code here
        M = len(s)
        N = len(t)

        if M < N:
            return ""

        # dp[x][y] - the minimum length of subsequence for s[:x+1] to include t[:y+1]
        dp = [[0] * N for _ in range(M)]
        dp2 = [list() for _ in range(M)]

        for x in range(M):
            for y in range(N):
                if s[x] == t[y]:
                    if y == 0:
                        dp[x][y] = 1
                        dp2[y].append((x, y, 1))
                    else:
                        for z in range(len(dp2[y-1]) - 1, -1, -1):
                            r, c, l = dp2[y-1][z]
                            if r < x:
                                dp[x][y] = l + x - r
                                dp2[y].append((x, y, l + x - r))
                                break

        mini = float("inf")
        mini_idx = -1
        for x in range(M):
            if dp[x][N-1] > 0 and mini > dp[x][N-1]:
                mini = dp[x][N-1]
                mini_idx = x

        if mini_idx == -1:
            return ""
        else:
            return s[mini_idx - mini + 1: mini_idx + 1]


s = "jmeqksfrsdcmsiwvaovztaqenprpvnbstl"
t = "u"

s = "abcdebdde"
t = "bde"

s = "fgrqsqsnodwmxzkzxwqegkndaa"
t = "kzed"

s = "spbmtkwqpftyahhnughzxscpavtqymtbanjyybdlhbphfrycpytsgzoeunvxaxuwbmecthomrjgmbvaoyjxxefmtxaxgwswdjdjlkpzsuirbujvhesfzdklgkulkmfnlofytaszwtxacnffvszmobxwmlhaxporskwzrvgmdpneggxqidqsdgvcprcnkdrxtsktibilbtggpazwuddhrgsmaspelglhausmfnyksdfyrwtpftrgtw"
t = "asgvamuyus"

s = "gmtfzvojtkeydxobnsjfothujtsglwwyaejwuyyqooanupgymjfqkzxuqynukrydctrzwjfsxpnicjywzqupeiahtslznfcqztblihuirushwjomfobemyguqgxbpgsvptzjsmitphpqkszplygukgsczttmpsqsvfektacqekylqfrslotvfysfvdomyistygztfscslkmhjotfnruzkqmmpsjzscfflaqvtvkecycazoabttucomrfbwmlghiwrvexvusoifquhvebocrvigtlyblksolibrjmrhuaqnvnbvepwavphbhllhwgxakupvlyoiwyqiitelwluzmvnizxrmjzhzuyrhjozatursqdhiyphqhzvzacayrbbumkplmqaqjiddgkdojncbdvrshsubtltkimfkgnskmtadnclyiiwlntqkedrtlraxjvlkucadzrpqkefbedfarsaraqmkdyqierhadcclayhxkblhqozajjpzbbjchhowrtnhkcdndwtzockgutgicplafxscknlyobxgdwnaduiifghlmbkayysggxhyzjusifspxooijzfsngrdbiyzewlgdasyliguusodgjhazeuvcibwpdfdghslbrebsktjqvdofymylespcvenvgmcxwybvymvylorgjzttqhdbjvshgomkgasknczfdfxyhgwqzikfbwjqkpwvybfxoknzgqzvwaeasqlgzdhvukwrngpjjxopkwwjsjobwagtklbrnaodykngvaxnpouvhhkedqdquwedohgylefftkjhbuwuastohmenqpqiyurisfggalhneyqnvbqhgvcutjrqnhaatqkprylumstafbeiimcefjcsdgeeyfgfpficgafhldlpxplsgqulqnedvyuwqrtuwoegwfxxvzqxkdxgzztjdudwcunlfwwzepgkjogbiqjgajoqckdfkmsppyztvgyrfzdrfesfpbmgbhbmrairktbuwpxvxiszuuhzauvjrybrbzxpnzaacjnicoqfbyguuvtyikotjmcuyzvxmbllhiiiiylnutnpleqkzycahcnjjfvdkushpokzwhmyalmlgsuptljvryhnzbwoysikmgkwocxqczmursxfrchxlamnamojzreuscfbtzntpfjwngqwsfstjmzbqjjbyqrmezdsmgifvexedsuzfbbfcxysrokdidaoeldwzjyswgpuxtnpmfmlbguifotaosekeobotyxeekzeoccqmqcqkepuuydyhvkhaatyudbxmpjpoultiubmhvniunimampmbdvdubtqtmqhwoacwwyabxjswaxtqcuxzxzmctdexxkklxprgbjhwjyhmrdljwptsnkuqwjsjbggfnuxqpznmsyjomjzbxgqrexkktdjfnknqnvgwiputidtuqnvbjpbgtkdpftmqgypgunvcqivlamodqudpsyaixuihdeljvurmvjdovoqyofblehwaalonlkbmuvzupgszdclifhrggmpcexpkwyzjoynttecsnmugbokhuwmjurhztkbpuzylttaagyzywwseqqorrclasvwolivkmxwcmsiicqumnphalrblzvtkfumfpeucpxywucfbglsuebmszzaqjdphdoljzmdabszvfmmevffmjwpufyvkgoynouocboswmntcxsejknphveksiiiuyfzcpzxjpoohdwkzocjxsegxpebuwukxtralbtyalotgoojmfumhzyftctdoolaspohmfquzrvadvraftzvsnjeziluxbvfvyfsjgyvphchplruyfnojbzarcmvwchwegumvflpbrkozhpuhwwmoiqwaizlqfmssqgrwtdncirdjupulwzvxcddwhkggluveikvcbtqfelenfewkfrwyzalhjanetggzwcpyhstjcienlpfshnrczkydintnnpvinmuaqbwljnqxnvrlqdgmzjbtmadvcthzmnltkewamzyfdcbxrhcvbgikjfsnynlnfrrlcygykmuoescvwgtcbbsmlngizrkbnyjipevialjiamavgnojwfnkjfmlpjvuvxlbewrpllfabgrsceidmaavmrapgismqdchlyawdokjjxzhsmrmyfoopuvaqnduldbjxpmeppvvrglbkjwajunoczylbapxoljddetnaducxzodypwzbwsqrpzehysqzkcyveswhamyimpomwxltmmalfewxuzikegqmikvzyxcqjgddrwsvjwgasgvvdougwcinakurfkcdwgcvqoutfiuuwsvhzxnptpqhkssszakfdweuytcdweswfjituzcnvkseqfkinjfvgkydbiqodmehhuhucbcvmqylkngabdsmqjzsmsteuiqrrfuchsxntfvfkxyhyyipmtuhaysmthzrnzgqqtifkmswcbqirfifjizuoeuwugrbvqhenopkaovthslrupiabufhpwfcwmykxduqidmhwktztdmhjbxxlaaxvmygvwphitkinwufzerkggxukizcezexhrgifqskidzvqqknsvptjafemmvsuicragwwkynamhxorbtjcvmlhpsnimudwtrydtvtrvffcxnhdxdtcurwqqvzqmskhqgvafalmdgavcgcmgsduvsqwuulikxgzwqoxtpaaftsljxbgjmzruuclvjbdqgupddeosipyxjmdshvjhtawmalbjozriwjkwarnhmkhhdhqzdzcziqpupvtvitdyojzuneelngfbxiwytvqdkriowvdcrpnqsugrzjcozsyewrjxnrmezupmtshhbdohnrufzwvlxwbbqjbzuzlznrrhrejnasylmyeugklgzyuoyaludqaksfqzcqwtmrrvbqunxmaqvqxmwnuukjfmmioeygveoakvmymakwascofyqfaynnjswnenkludvwgrrsckahogwuzktzwqimazrkisahoigiovptuuqwenktuzhaglhgtmifayiwveuwdqjtbaqywzaplhkuiktqmfgutadvwjijnyyuazldkmqvssvdvmtxoohldowsnselqjtnyxddzxdgxdvkvejgxjyjvruhscbkkrmzckjuwgtdbswbicftsyrbuzuwshsqliwbjztuuyujkdmagzdksdmjslkjgaivezuwpiqpylhwijfcxardgepjbutyjmzujqyytnuxuyrqkjigedtmrlnvmynpaqmwmrdbotdiyoibqyedqgzlerdqidrgedcwauvjzppnbulonlkdlkaznioyfiqpldqfxphamgkzjatspuxknylcgyjosrlqskesowuhnisjrdrrktgrhkgkfmoigameikmjmfhdytkhwokolshedxueclcqdpxrxcgrjgffclziyejpofzlxqufuggpreawrehcxmqdyozdmfffqcmomwwpzcmdkoaiwzcmwhtwrbipbiwknpjpxdptrvuxrnjkctmfhdezkooaonwpajybxafqeljyvtphwzsucwhqofiypagbvapondwbwbpobadjavjownfesrjhpqjgzwmgpuegwwbtkymrsdtmxhvqzyxnhobizihklidhhaicsyfovnitatecvccaijjigfvqklmutjxoryhxafdjqasqfapjfvsrcvizjlgaelyggsoczjzebyuetiymodydwkxeawtopvtfecbieactkjhflqgydlmczdwforsbwrgpcdssznovasaqzgoftizxdvjwzvezvzecmclxljmsuzftzjvcrlzvosaoyxoeklatengigecsdkxpquhoiqykwjiqsdidwnracdnncuihqujiqybvbkqmujsnhjmhxfsgnvsgctlkqpobfolqezmpuaksbrcniiesdorqgjuaeisjztdmvemnzdskhuvlegdpkqfnlyuzoicipkrydemiltibegvmkhvtaovqhmiljtrsapmwmrzvdghflhhjtosallsbsdwbebvclpuyojfnropgffeblwpgcrpnkzqqbfbidbxiromghmwlrmtsaehvcrhslkopgujlflbpyjsuyrttvnhbpvgnccfaiiqcpcnfdleyqoowrwlhhnjapvpzauuxnhgoguqyuyojxjamgbhhgoqylshuycfknkmegeulcpgxwtnflawlvfxvmjjkmbtvsuifyazllerxofsvzzqxwkyoypaiztkxngjlmjzvzqxefbdtampgttovwcokszweztddxfgbsrcgltpodpdaczaoycsolgjdsokemflnwvumxavxufouhjihnnofegprbhggmeuynqydlafzfyuyasikljikclnmiyuaseisuxxgartjyrhxyojzloqpxcksareuvimuofiepawqrvnegvjovizdfstpnnnrkclsmcquplrmqaikfrjjgozfbmpuamfjxxuyxgvcqnkremowstzdylvmsbfzxzfycfrcuwyxgptdvpydovrljeynubgwyrdryrzuicpputzrageqjxwxrkvmjihrmfzgokxnportavzmcwsfzexpveenrwhdumfsumuguaxmbwaxrfnnqjydsnimgvtolwvvnolwscfkfetgpmnfnnqwlahhacladnamysrlzingevqzxrvqjcsaguwoibialaghptcvodyckzyvpeghdqyawkwvolqpjhtcidfwaoooybhuawmhqdouecqcqbfcukesamdmpqejujjozeeudpxfhdpylrpwncsqewzpkysroqppzbjbtutskefnahyswxplnhezazbalrnvgqmpnmdpgodvmtuylzwbbopfyexittevlqjqhzkmofgvtalhhqxuwosgkouhvwemnoutafujtlhurgxxofuzfjhvsicqoxsyqytelnwrhzbmyxyrjbkficohvqpdccxapchlagawjpzjglvxgbbiuylnjnfjcghsrbhkjcqybzphdcmvbebealicjezenlbdkzbdbdbwccpifpamuhuxphehqqjiyodqgydoztvbfgcwivrkcrfdrrepwbgkrchgzzykxinbixcooyxmajyttmqhndzuxksdixbtxzxrxdblfwsotlnuqiiyoceosogwwmvowkihnleshalqvowyozoxwfmdullyxedjjghgrylueuntbvrjwqwstjljqnqaikwaputqevjicomcvutinqtoeliknlbonbzkiqpavhxuhrekmuixldvvbuwhtamnojmvcbjdbidznynxlomiunvicqwyzcsfopubotsjfibevqjlmhlbwncpreshwpowrxagqxihbfmfuxitybbfoqlsqsfrxhsmiupfcjwjsopfotigkaekmxdcclzissqlmuadgckpkhqjeccineuxognbnbwltfxbglxizfghlguordwlauhmanfymxbtnyswscjdyzslolfqxoploqjvruczjydarxgapkexkvfxplrffdxtufbevtkxuahkdrwlvdskdefpkxzppjbfmwkqoizchkfyksrflaaoybhjfwbscekeitjjykcpsvnnuoeppkbrwjloassjrhdgwgqzbheqpkivxcoxldinnzvzxqorxymdlfgrvzhcyemyqnlvylxiialihsylcgynuupsaipojuyuvdegnwnneymmqgjzzzoadflgqlvotgwlfbevcrogohqfpnogggwkqoypdknegftjdpjqyaimiqjqifdpsjouuthomszolxoegeiwozuyxunsfpsmcusvlpjurwnundcnlwdynvzvlcdmrgxsykuzlikxxcnheqixmpqwforthwzgzsaviijxgkjukxomialxutoxmqaznlpsuhuhumespsarqkfwjbtbazdcgqobwbneldagzaocuhzmintkklrgfexcrbdnlmxhucickdzssgbsltnfjadccsaqnrwrkxlkgkczoulxzxsvojfnssjeqcznufopvharftmwilqaqkysmesdauepxrbwkmdgbqhfzaeozbbzxcuujgodvbvqeuvhaxcjmotqaqxmwbklnmheficpbapweyvnolwbuusycxxvoqseqycnnyqztbotttqaaraweaxetoegxsnrkqnqftxwzdkrllqqxiaplnjnuohmwdvrxoqpwlrpgzwabxhpcdutjrwguldirphlwiinrjptssrktiubaanwjmmqxwumtmvmedzbptbfhifegexbomefcsjzensfmntaazoqaszpjlsvrlsgsjfcpbjfpafpfokybdrsonserxzfwclspezkqpruvkcdbfwzihwoccnweyihxqzmmkaowcfehbtsbuikbnvxowhpahixifjixqsediferewfbrrstpshmzqrnrojdnksjvajhpidjssmaawrbvkdwcxjvgmbgldygxdebfjwslbnmcqbgzoigiysredxgymyojvwljiwalycxtfnmczememmjsmbnwxedapsfdrwklwsfphjvrbkjpmiwaclnqxfogiwbrkcnlzgrmgbpwxygkbwtmtghcwiuquqnoiooggobfgfxyuyngqvlssifxuffhhwygbewrumrkdgvwhpicxgkdbftwlfakcotjiwfupmmvpxvvqgzrzmcpucuczjgotrquxmfndedkqdubghnvonhswafsddkpslkvupzdcphnnqujetfchxjojccycizajrqolbdydgbzscieuadtmihkmlkyyxjyebeocvcdsnrlmxvbzzceoxdzccglibnjorrutnyktupqeyviroxarbxhlvzhjtiezqxwtrecufqexqskbeqfsszsmzgjymefbxqavjxxwfrgbdiplpapewpxwnbjkxladxlqwnqyvxbgmkfbwecanyytrlzsgtkxtcykpinjqtycrorxjsqvhzroxpevycsovyuprhyuhbwrbbzoajkwzcmqpfifppncjasembidviflesnpvyubbdklxjafyoyvnlcurggyghobdwamfedervrgkehpcdfyccryafnvgeailzizhhijygselucomniqhcmelvkuzxqdwtdofwwjohlerasweqdaqgwkfkbuctuyjxkanqsoxkuyigvghlzfibfbpegkbanlnllsqulvjpkapvefkguzwovshjgusgcaazzojcgipwhajsxhuvauvstbxlrdbignmxwtuudxhnzanaqqxhyyuajcvujegpdjrzwxpfgcampwbudmkkchstuatzgaoxqbnpnkaqkrubmvakzlugipsqzzudauomcvczvygnfnkfmdzngquvlgvtjhgqkxlcydkbhocqouigcdgtsbelqzjlapvckdrdvlqilfziifsfwgwovxlzffifxskqgegqqkzqkftqaduhuowxftjqtqnetabaxbooecuzbgqtbfehwmknbwnpgzixtnkyemrvsgaykcqxbvdhrkoesxdnaihyrmuuheiovcxentdyfjbmgacotqxdwafqqlhxohkapxuthnxubijlynbgwnblegbpdsuhqruztluxaegrkabbkenzbvzpnswjjgesreeclxpgvdidbcwiabbpojuqguoqmkcmjxfenpulnyhvwaaahnqtwsylqrnpgkqtecfbnhvpzfhfarcawovrqpdqyoplypkhpsfhmteebnzweyuffkxptepzxzsyyhvcpxoyoihvvmqaqpefzaiwapmxwgbvloxgcwonkbpuwclvqjvqgshqwbwqtcbxmkjmouaigvcxsihexhetcsndmvtqdemgsxququfeqtryuaqcxgxenksxvdcwkfkmmyfmdkoagbgikbuascqednfzztkemasaxxkgfwhmxtwprcbczmkqyntkpvqyeaksvcrselrjbybtmnuejbudilohvxweiozmwwpdxuohtwtjqfgyxkrscryqidpwxllnfgkzrkmlmkqrzocuuswpxtemduqfnqrbtunhwziqwnsdjwaagwdsyqeaxzbswblnzxpzibonskhbwrcvjrlstvbymdfwqbyjbuvyqkowpkyjdrrlfgzgxynxrktsejddahqrqabxyehhyowvtipjyxbfkiwjuegyksiwvctiprbzuvwlrxlojvllklgikkcsittydaavrlinsxdeyvmsnznhfiswsesnyjghtropxkoyopfhfoafiuesgmbpozwzqhivtypnlepvltpkpgkdwsnicipmbqgmceyfbryzcirxjrioqceantjwpzupsghupjzctxdpnaqrizkocxffwzpzdkkbltdlfmzynhwpqzfcuxeafxqczsiokmdtxylnbbkizwbqcuqkzssyvblzcmagepydgulzpalautnwyspqeibrprgpufzbwkpxuxbtwsjdltcmppjtpjwyzebgvpjsyqnupmyiagylbafnqfudibhfkiactnjhmwaqofgwtrtaagpqbeqqmknaohwribzsjbkcxpilqzjvdrpkdsuriyhmhdulpybsydxkvzymteqokhlzdalgkufkyzwccmwpnidjurhxqfpibclzbrukrlndyadirzhjnunntqqiytrelbtbrhyfblusoyuefdevaydunopetbfhjrjjkuuufhlgrbajplyfqdbqgbewaebohpalrbybnbwusttmftxysnwulfqvypxmlqatdjhceevdbknqkkzpvcctvrigwbbzddubnrptekycuujrjuieyiyxffircoetcxbjbwogqvtkqnburpasjkzhiwaygbyaaghnosfanegdcbiafufsgpxaizyisbuadejpccyyiwhhdcwywxxfwigmswegbnfyryfuxrfgmiprkgxyiyadixcdninyfplxwxjsesngsebuqdnwdtqivvyhoolxplrqbdnjdzlnnokmzorxjeaavazqcxeniiileldwgtyuojntyrnlzthschhgawjsadnlijqnwaumrfggcsvsethgrlmkksakdlbvfrdrpwkghzsfylqxzqmdhvjncmdvoezcdlgsoytuwoalarssvsmbwnryebggemavchpdzqxhlldxdbokilpxlvzacbxcpuqoosamnxslqdhgtshifxwkjjbdehdxotjwlwusjtmrjgmoqrxbrutresioryfpjpweeksgurppfivddhjvzgpodcrzepfhlfuyasbhootggkvwqilqgplzesnamdiznipokhcdabvuwrpnxvqwwxkvtiraykpmudsothlxiszhhygqujstarllfbwvtmhqyfrnjrfebiwdcezzlgrpsbnxvbviubddggazizhrnlnrtvbylcleswmzkujoxkxotejgttkhugfobqmewcouvkfpyewgosfunicqwkthaebsctaylnziybkaqssnyxespwhfzahvmzsibeyrlzmnppnsvgbaocjzvokryaqgdzifcupdkvpvxlpypvxljkoykibvsrhhnrivrgqxkctlvnfhdniwzpwesysjdwpebeosqyapcsomoekaosbkfwjynbpkgjxqeegqropftbestemwkfhnhursspjjvqwotsbtaiqciaelicyfbxgvmystbgelpgcsisbcicxvfagucmboigyzxkwkfdblzmgaoobxtvnoibbvdeyixvmmfpowrkoelapnbakxhesapxanqtkmaqzlxsdmbgvuzfyytxefivapcnlcycxhdikeynnroovxzavmbknblzhyldmeebqfmhuuqczzkddxqqkseojlmswlwncrtrjrtrhgngzvlxhnqcsguwpznfzsgjeeyiutznkbamdneeospbebynnwfavpupzbixljqvtdncavhwawsrwbstrjzfmuocfrikltlvdeqcwpfovvuwnlugspjgruryavpwbtmpk"
t = "misqtbommivohnlqwdbryzarxxbwsmwnthkbzxcvwhxymlzkrirszlsiyrbaztnpsfutqyukiztfhlxkaccezmtwcqkosfcvwxyb"

solution = Solution()
print(solution.min_window(s, t))
